#!/bin/bash

echo "Restoring old emoji preferences..."
if [ -f "/Library/Emoji83/com.apple.EmojiPreferences.plist" ];then
	mv /Library/Emoji83/com.apple.EmojiPreferences.plist /private/var/mobile/Library/Preferences/com.apple.EmojiPreferences.plist
else
	echo "Could not find the preferences."
fi

echo "Done."
